<a href="https://colab.research.google.com/github/esosikeyes/Linear-Algebra_2nd-Sem/blob/main/Activity_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Linear Algebra for ChE  
##Laboratory 2 : Matrices

Now that you have a fundamental knowledge




##Objectives



#Discussion

In [4]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

#Matrices

The notation and use of matrices is probably one of the fundamentals of modern computing. Matrices are also handy representations of complex equations or multiple inter-related equations from 2-dimensional equations to even hundreds and thousands of them. 

Let's say for example you have *A* and *B* as system of equation.

$$
A = \left\{
    \begin{array}\
        x + y \\ 
        4x - 10y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        x+y+z \\ 
        3x -2y -z \\
        -x + 4y +2z
    \end{array}
\right. \\
C = \left\{
  \begin{array}\
  w-2x+3y-4z \\
  3w-x -2y + z \\
  2w - x + 3y - 2z
  \end{array}
\right. $$


We could see that A is a system of 2 equations with 2 parameters. While B is a system of 3 equations with 3 parameters. We can represent them as matrices as:

$$
A=\begin{bmatrix} 1 & 1 \\ 4 & {-10}\end{bmatrix} \\
B=\begin{bmatrix} 1 & 1 & 1 \\ 3 & -2 & -1 \\ -1 & 4 & 2\end{bmatrix}\\
C+\begin{bmatrix} 1 & -2 & 3 & -4 \\ 3 & -1 & -2 & 1\\ 2 & -1 & 3 & -2\end{bmatrix}
$$


So assuming that you already discussed the fundamental representation of matrices, their types, and operations. We'll proceed in doing them in here in Python.

##Declaring Matrices

$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$


In [49]:
## Since we'll keep on describing matrices. Let's make a function.
def describe_mat(matrix):
  print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [48]:
##Declaring a 2 x 2 matrix
A = np.array([
    [1, 2],
    [3, 1]
])
describe_mat(A)

Matrix:
[[1 2]
 [3 1]]

Shape:	(2, 2)
Rank:	2
Is Square: True



In [50]:
B = np.array([
              [8, 2],
              [5, 4],
              [1, 1]
])
describe_mat(B)

Matrix:
[[8 2]
 [5 4]
 [1 1]]

Shape:	(3, 2)
Rank:	2



In [51]:
H = np.array([11, 22, 33, 44, 55])
describe_mat(H)

Matrix:
[11 22 33 44 55]

Shape:	(5,)
Rank:	1



#Categorizing Matrices

##According to Shape

####Row and Columns

In [52]:
row_mat_1D = np.array([
                       5, 10, 15
]) 
row_mat_2D = np.array([
                       [10, 20, 30, -40]
])
describe_mat(row_mat_1D)
describe_mat(row_mat_2D)

Matrix:
[ 5 10 15]

Shape:	(3,)
Rank:	1

Matrix:
[[ 10  20  30 -40]]

Shape:	(1, 4)
Rank:	2



In [53]:
col_mat = np.array([
                    [56],
                    [73],
                    [87]
])
describe_mat(col_mat)

Matrix:
[[56]
 [73]
 [87]]

Shape:	(3, 1)
Rank:	2



####Square Matrices

In [54]:
def describe_mat(matrix):
  is_square = True if matrix.shape[0] == matrix.shape[1] else False 
  print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')

In [55]:
square_mat = np.array([
                       [5, 10, 15],
                       [4, 8, 12],
                       [3, 6, 9]
                       
])

non_square_mat = np.array([
                           [9, 18, 27],
                           [8, 16, 24]
])
describe_mat(square_mat)
describe_mat(non_square_mat)

Matrix:
[[ 5 10 15]
 [ 4  8 12]
 [ 3  6  9]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[ 9 18 27]
 [ 8 16 24]]

Shape:	(2, 3)
Rank:	2
Is Square: False



#According to element values

####Null Matrix

In [60]:
def describe_mat(matrix):
  if matrix.size > 0:
    is_square = True if matrix.shape[0] == matrix.shape[1] else False 
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
  else: 
    print('Matrix is Null')

In [61]:
null_mat = np.array([])
describe_mat(null_mat)

Matrix is Null


####Zero Matrix

In [62]:
zero_mat_row = np.zeros((1,2))
zero_mat_sqr = np.zeros((2,2))
zero_mat_rct = np.zeros((3,2))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')

Zero Row Matrix: 
[[0. 0.]]
Zero Square Matrix: 
[[0. 0.]
 [0. 0.]]
Zero Rectangular Matrix: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]


####Ones Matrix

In [63]:
ones_mat_row = np.ones((1,2))
ones_mat_sqr = np.ones((2,2))
ones_mat_rct = np.ones((3,2))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')

Ones Row Matrix: 
[[1. 1.]]
Ones Square Matrix: 
[[1. 1.]
 [1. 1.]]
Ones Rectangular Matrix: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]


####Diagonal Matrix

In [64]:
np.array([
          [2, 0, 0],
          [3, 6, 9],
          [5, 6, 9]
])

array([[2, 0, 0],
       [3, 6, 9],
       [5, 6, 9]])

In [66]:
d = np.diag([9, 8, 7, 6])
d

array([[9, 0, 0, 0],
       [0, 8, 0, 0],
       [0, 0, 7, 0],
       [0, 0, 0, 6]])

In [68]:
d = np.diag([9, 8, 7, 6])
d.shape[0] == d.shape[1]

True

####Identity Matrix

In [69]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [70]:
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

####Upper Triangular Matrix

In [77]:
np.array([
          [3, 5, 6, 6],
          [0, 2, 8, 5],
          [0, 0, 4, 7],
          [0, 0, 0, 9]
])

array([[3, 5, 6, 6],
       [0, 2, 8, 5],
       [0, 0, 4, 7],
       [0, 0, 0, 9]])

####Lower Triangular Matrix

In [76]:
np.array([
          [5, 0, 0],
          [2, 3, 0],
          [4, 7, 9]
])

array([[5, 0, 0],
       [2, 3, 0],
       [4, 7, 9]])

###Practice

1. Given the linear combination below, try to create a corresponding matrix representing it.

:$$\theta = 5x + 3y - z$$


2. Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix.  

$$
A = \left\{\begin{array}
5x_1 + 2x_2 +x_3\\
4x_2 - x_3\\
10x_3
\end{array}\right.
$$


3. Given the matrix below, express it as a linear combination in a markdown and a LaTeX markdown.


In [80]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])

4. Given the matrix below, display the output as a laTex markdown also express it as a system of linear 

In [79]:
H = np.tril(G)
H

array([[1, 0, 0],
       [2, 2, 0],
       [4, 6, 7]])

##Matrix Algebra

###Addition

In [82]:
A = np.array([
              [3, 4],
              [4, 8],
              [9, 2]
])
B = np.array([
              [7, 9],
              [4, 6],
              [3, 5]
])
A+B

array([[10, 13],
       [ 8, 14],
       [12,  7]])

In [83]:
2+A ##Broadcasting

array([[ 5,  6],
       [ 6, 10],
       [11,  4]])

###Subtraction

In [84]:
A = np.array([
              [3, 4],
              [4, 8],
              [9, 2]
])
B = np.array([
              [7, 9],
              [4, 6],
              [3, 5]
])
A-B

array([[-4, -5],
       [ 0,  2],
       [ 6, -3]])

In [85]:
2-A ##Broadcasting

array([[-1, -2],
       [-2, -6],
       [-7,  0]])

###Element-wise Multiplication

In [86]:
A*B
np.multiply(A, B)

array([[21, 36],
       [16, 48],
       [27, 10]])

In [87]:
2*A

array([[ 6,  8],
       [ 8, 16],
       [18,  4]])

In [88]:
A@B

ValueError: ignored

#Activity