<a href="https://colab.research.google.com/github/esosikeyes/Linear-Algebra_2nd-Sem/blob/main/Assignment_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Linear Algebra for ChE

#Discussion

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

#Transposition

$$
A=\begin{bmatrix} 1 & 2 & 5 \\ 5 & {-1} & 0 \\ 0 & {-3} & 3 \end{bmatrix}
$$


$$
A^T=\begin{bmatrix} 1 & 2 & 5 \\ 5 & {-1} & 0 \\ 0 & {-3} & 3 \end{bmatrix}
$$

In [6]:
A = np.array([
              [53, 22, 34],
              [77, 83 ,96],
              [20, 32, 44]

])
A

array([[53, 22, 34],
       [77, 83, 96],
       [20, 32, 44]])

In [7]:
AT1 = np.transpose(A)
AT1

array([[53, 77, 20],
       [22, 83, 32],
       [34, 96, 44]])

In [9]:
AT2 = A.T
AT2

array([[53, 77, 20],
       [22, 83, 32],
       [34, 96, 44]])

In [10]:
np.array_equiv(AT1, AT2)

True

In [15]:
B = np.array([
              [11, 22, 33, 44, 1],
              [55, 66, 77, 88, 2],
              [99, 100, 110, 120, 3]
])
B.shape

(3, 5)

In [16]:
np.transpose(B).shape

(5, 3)

In [17]:
B.T.shape

(5, 3)

#Dot Product / Inner Product

In [19]:
X = np.array([
              [3, 6],
              [9, 12]      
])

Y = np.array([
              [3, 6, 1, 3, 5],
              [9, 12, 7, 9, 11]      
])

In [21]:
np.array_equiv(X, Y)

False

In [20]:
np.dot(X, Y)

array([[ 63,  90,  45,  63,  81],
       [135, 198,  93, 135, 177]])

In [22]:
X @ Y

array([[ 63,  90,  45,  63,  81],
       [135, 198,  93, 135, 177]])

In [23]:
np.matmul(X, Y)

array([[ 63,  90,  45,  63,  81],
       [135, 198,  93, 135, 177]])

In [ ]:
D = np.array([
              [10, 20, 30],
              [40, 50, 60]
])

#Rule 1

In [25]:
L = np.array([
              [3, 6, 1, 3, 5],
              [9, 12, 7, 9, 11]      
])

M = np.array([
              [2, 4, 5, 6, 7],
              [9, 8, 7, 6, 5]      
])

N = np.array([
              [3, 6, 1, 3, 5],
              [9, 12, 7, 9, 11],
              [12, 24, 36, 42, 54],
              [11, 22, 33, 44, 55],
              [10, 20, 30, 40, 50]

])

In [26]:
np.dot(L, N)

array([[ 158,  280,  330,  437,  550],
       [ 428,  784,  972, 1265, 1600]])

In [27]:
np.dot(M, N)

array([[ 238,  452,  618,  796, 1004],
       [ 299,  550,  665,  857, 1091]])

In [28]:
L @ N

array([[ 158,  280,  330,  437,  550],
       [ 428,  784,  972, 1265, 1600]])

In [29]:
M @ N

array([[ 238,  452,  618,  796, 1004],
       [ 299,  550,  665,  857, 1091]])

In [30]:
np.matmul(L, N)

array([[ 158,  280,  330,  437,  550],
       [ 428,  784,  972, 1265, 1600]])

In [31]:
np.matmul(M, N)

array([[ 238,  452,  618,  796, 1004],
       [ 299,  550,  665,  857, 1091]])

#Rule 2

In [43]:
A = np.array([
              [3, 6, 1, 3, 5],
              [9, 12, 7, 9, 11],
              [2, 5, 6, 9, 2]      
])

B = np.array([
              [3, 6, 1],
              [9, 12, 5],
              [12, 24, 36],
              [11, 22, 33],
              [10, 20, 30]

])

C = np.array([
              [2, 4, 5],
              [9, 8, 7],
              [10, 15, 34]
])



In [40]:
X = A @ B
X

array([[158, 280, 318],
       [428, 784, 948],
       [242, 454, 600]])

In [41]:
Y = B @ A
Y

array([[ 65,  95,  51,  72,  83],
       [145, 223, 123, 180, 187],
       [324, 540, 396, 576, 396],
       [297, 495, 363, 528, 363],
       [270, 450, 330, 480, 330]])

In [42]:
np.array_equiv(X, Y)

False

In [44]:
C @ (A @ B)

array([[ 3238,  5966,  7428],
       [ 6540, 11970, 14646],
       [16228, 29996, 37800]])

In [45]:
A @ (B @ C)

array([[ 6016,  7642, 13562],
       [17392, 22204, 39860],
       [10570, 13600, 24788]])

#Determinant

In [52]:
A = np.array([
              [1, 4],
              [3, 7]
])
np.linalg.det(A)

-5.000000000000001

In [53]:
B = np.array([
              [1, 4, 5],
              [3, 7, 1],
              [9, 5, 2]
])
np.linalg.det(B)

-219.00000000000003

#Inverse

In [61]:
T = np.array([
              [4, 6, 7, 8],
              [8, 7, 6, 5],
              [1, 2, 3, 4],
              [9, 3, 4, 1]

])
np.array(T @ np.linalg.inv(T), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [59]:
Q = np.array([
              [3, 6, 1],
              [9, 12, 7],
              [2, 5, 6]      
])

V = np.linalg.inv(Q)
V

array([[-0.34259259,  0.28703704, -0.27777778],
       [ 0.37037037, -0.14814815,  0.11111111],
       [-0.19444444,  0.02777778,  0.16666667]])