<a href="https://colab.research.google.com/github/esosikeyes/Linear-Algebra_2nd-Sem/blob/main/Assignment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Linear Algebra for ChE  
##Laboratory 2 : Matrices

##Objectives



The objective of this laboratory activity is for the students to be familiar with matrices and their relation to linear equations. In addition, for the students to perform basic matrix operations. Lastly, for the students to program and translate matrix equations and operations using Python.


#Discussion

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

#Matrices

A matrix is a rectangular-arrays of numbers, symbols, or expressions, arranged in rows and columns. Matrices can be used to compactly write and work with multiple linear equations, that is, a system of linear equations. 

Written in the module, matrices are useful representations of complex equations or many interconnected equations, ranging from two-dimensional to hundreds or thousands of them.

$$
A = \left\{
    \begin{array}\
        x + y \\ 
        4x - 10y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        x+y+z \\ 
        3x -2y -z \\
        -x + 4y +2z
    \end{array}
\right. \\
C = \left\{
  \begin{array}\
  w-2x+3y-4z \\
  3w-x -2y + z \\
  2w - x + 3y - 2z
  \end{array}
\right. $$


In the Figure 1, it contains the A and B as the system of equation. Whereas, A is a system of 2 equations with 2 parameters. While B is a system of 3 equations with 2 parameters. It can be represented using Figure 2 as matrices in the following way:

$$
A=\begin{bmatrix} 1 & 1 \\ 4 & {-10}\end{bmatrix} \\
B=\begin{bmatrix} 1 & 1 & 1 \\ 3 & -2 & -1 \\ -1 & 4 & 2\end{bmatrix}\\
C+\begin{bmatrix} 1 & -2 & 3 & -4 \\ 3 & -1 & -2 & 1\\ 2 & -1 & 3 & -2\end{bmatrix}
$$


##Declaring Matrices

Box brackets are widely used to write matrices. Rows and columns are the horizontal and vertical lines of entries in a matrix, respectively. A matrix's size is determined by the number of rows and columns it contains. Matrix A, for example, has two rows and three columns as shown in Figure 3. A matrix with m rows and n columns is called an m × n matrix or m-by-n matrix, while m and n are called its Matrix Dimensions [1].

$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$


Each element of a matrix is often denoted by a variable with two subscripts. For instance, a2,1 represents the element at the second row and first column of a matrix A. Thus, this is called Matrix Dimensions. In addition, a matrix's individual components (numbers, symbols, or expressions) are referred to as its elements or entries [2].

Two matrices can be added or subtracted element by element as long as they are the same size, such as having the same number of rows and columns. The rule for matrix multiplication, on the other hand, is that two matrices can only be multiplied if the first's number of columns equals the second's number of rows. A scalar from the related field can be multiplied element-by-element by any matrix [2].

In [ ]:
## Since we'll keep on describing matrices. Let's make a function.
def describe_mat(matrix):
  print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [ ]:
##Declaring a 2 x 2 matrix
A = np.array([
    [1, 2],
    [3, 1]
])
describe_mat(A)

Matrix:
[[1 2]
 [3 1]]

Shape:	(2, 2)
Rank:	2
Is Square: True



In [ ]:
B = np.array([
              [8, 2],
              [5, 4],
              [1, 1]
])
describe_mat(B)

Matrix:
[[8 2]
 [5 4]
 [1 1]]

Shape:	(3, 2)
Rank:	2



In [ ]:
H = np.array([11, 22, 33, 44, 55])
describe_mat(H)

Matrix:
[11 22 33 44 55]

Shape:	(5,)
Rank:	1



#Categorizing Matrices

Matrixes can be classified in a variety of ways. One may be based on their shape, while the other could be based on their element values.

##According to Shape

####Row and Columns

A row vector, also called a row matrix is a 1-by-n matrix, while a column vector or known as a column matrix is a n-by-1 matrix. Both kinds of vectors get their names from their resemblance to the rows and columns of a matrix, respectively [3]. Rows and Columns Matrices represent the row and column spaces of a bigger vector space. Row and column matrices are represented by a single column or single row.

In [ ]:
row_mat_1D = np.array([
                       5, 10, 15
]) 
row_mat_2D = np.array([
                       [10, 20, 30, -40]
])
describe_mat(row_mat_1D)
describe_mat(row_mat_2D)

Matrix:
[ 5 10 15]

Shape:	(3,)
Rank:	1

Matrix:
[[ 10  20  30 -40]]

Shape:	(1, 4)
Rank:	2



In [ ]:
col_mat = np.array([
                    [56],
                    [73],
                    [87]
])
describe_mat(col_mat)

Matrix:
[[56]
 [73]
 [87]]

Shape:	(3, 1)
Rank:	2



####Square Matrices

A square matrix is an important format of a matrix and it has the perfect square number of elements, thus, the number of rows and columns are equal. Its order is of the form n × n. All matrix operations such as transpose, determinant, adjoint, and inverse, as well as matrices' mathematical operations, apply to a square matrix. In addition, a square matrix can be used to solve quadratic equations in two variables [4].

In [ ]:
def describe_mat(matrix):
  is_square = True if matrix.shape[0] == matrix.shape[1] else False 
  print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')

In [ ]:
square_mat = np.array([
                       [5, 10, 15],
                       [4, 8, 12],
                       [3, 6, 9]
                       
])

non_square_mat = np.array([
                           [9, 18, 27],
                           [8, 16, 24]
])
describe_mat(square_mat)
describe_mat(non_square_mat)

Matrix:
[[ 5 10 15]
 [ 4  8 12]
 [ 3  6  9]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[ 9 18 27]
 [ 8 16 24]]

Shape:	(2, 3)
Rank:	2
Is Square: False



#According to element values

####Null Matrix

A null matrix is a matrix in which contains no elements. The null matrix is always a subspace of any vector or matrix.

In [ ]:
def describe_mat(matrix):
  if matrix.size > 0:
    is_square = True if matrix.shape[0] == matrix.shape[1] else False 
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
  else: 
    print('Matrix is Null')

In [ ]:
null_mat = np.array([])
describe_mat(null_mat)

Matrix is Null


####Zero Matrix

A zero matrix is a matrix made up entirely of zero elements. It is the additive identity for matrix addition [5]. The zero matrix works in the same way that the number zero does with real numbers.

In [ ]:
zero_mat_row = np.zeros((1,2))
zero_mat_sqr = np.zeros((2,2))
zero_mat_rct = np.zeros((3,2))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')

Zero Row Matrix: 
[[0. 0.]]
Zero Square Matrix: 
[[0. 0.]
 [0. 0.]]
Zero Rectangular Matrix: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]


####Ones Matrix

A ones matrix or matrix of ones is a matrix where every element is equal to one, and it can be any rectangular matrix, similar to the zero matrices.

In [ ]:
ones_mat_row = np.ones((1,2))
ones_mat_sqr = np.ones((2,2))
ones_mat_rct = np.ones((3,2))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')

Ones Row Matrix: 
[[1. 1.]]
Ones Square Matrix: 
[[1. 1.]
 [1. 1.]]
Ones Rectangular Matrix: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]


####Diagonal Matrix

A diagonal matrix is a square matrix in which every element except the principal diagonal elements is zero [6]. Elements of the main diagonal can either be zero or nonzero.

In [ ]:
np.array([
          [2, 0, 0],
          [3, 6, 9],
          [5, 6, 9]
])

array([[2, 0, 0],
       [3, 6, 9],
       [5, 6, 9]])

In [ ]:
d = np.diag([9, 8, 7, 6])
d

array([[9, 0, 0, 0],
       [0, 8, 0, 0],
       [0, 0, 7, 0],
       [0, 0, 0, 6]])

In [ ]:
d = np.diag([9, 8, 7, 6])
d.shape[0] == d.shape[1]

True

####Identity Matrix

An identity matrix is a square matrix of any order that has one value on its principal diagonal elements and zero values on the remainder of the matrix components [7]. The identity matrix plays a similar role in operations with matrices as the number 1 plays in operations with real numbers.

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

####Upper Triangular Matrix

An upper triangular matrix has all the elements below the main diagonal as zero [8].

In [ ]:
np.array([
          [3, 5, 6, 6],
          [0, 2, 8, 5],
          [0, 0, 4, 7],
          [0, 0, 0, 9]
])

array([[3, 5, 6, 6],
       [0, 2, 8, 5],
       [0, 0, 4, 7],
       [0, 0, 0, 9]])

####Lower Triangular Matrix

A lower triangular matrix is the matrix that has elements above the main diagonal as zero [8].

In [ ]:
np.array([
          [5, 0, 0],
          [2, 3, 0],
          [4, 7, 9]
])

array([[5, 0, 0],
       [2, 3, 0],
       [4, 7, 9]])

#Practice

1. Given the linear combination below, try to create a corresponding matrix representing it.

:$$\theta = 5x + 3y - z$$

$$
\theta=\begin{bmatrix} 1 & 3 & {-1}\end{bmatrix}
$$


2. Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix.

$$
A = \left\{\begin{array}
5x_1 + 2x_2 +x_3\\
4x_2 - x_3\\
10x_3
\end{array}\right.
$$

$$
A=\begin{bmatrix} 1 & 2 & 1\\ 0 & 4 & {-1}\\ 0 & 0 & 10\end{bmatrix}
$$

The matrix above is an upper triangular matrix where the entries above the main diagonal are entries with non zero number while the entries below the main diagonal line are all zeroes (0).

3. Given the matrix below, express it as a linear combination in a markdown and a LaTeX markdown

In [ ]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])
G

array([[1, 7, 8],
       [2, 2, 2],
       [4, 6, 7]])

$$
G = \left\{\begin{array}
1x_1 + 7x_2 +8x_3\\
2x_1 + 2x_2 + 2x_3\\
4x_1 + 6x_2 + 7x_3
\end{array}\right.
$$

$$
G=\begin{bmatrix} 1 & 7 & 8\\ 2 & 2 & 2\\ 4 & 6 & 7\end{bmatrix}
$$

4. Given the matrix below, display the output as a LaTeX markdown also express it as a system of linear combinations.

In [ ]:
H = np.tril(G)
H

array([[1, 0, 0],
       [2, 2, 0],
       [4, 6, 7]])

$$
H = \left\{\begin{array}
1x_1\\
2x_1 + 2x_2 \\
4x_1 + 6x_2 + 7x_3
\end{array}\right.
$$

$$
H=\begin{bmatrix} 1 & 0 & 0\\ 2 & 2 & 0\\ 4 & 6 & 7\end{bmatrix}
$$

##Matrix Algebra

###Addition

In [ ]:
A = np.array([
              [3, 4],
              [4, 8],
              [9, 2]
])
B = np.array([
              [7, 9],
              [4, 6],
              [3, 5]
])
A+B

array([[10, 13],
       [ 8, 14],
       [12,  7]])

In [ ]:
2+A ##Broadcasting

array([[ 5,  6],
       [ 6, 10],
       [11,  4]])

###Subtraction

In [ ]:
A = np.array([
              [3, 4],
              [4, 8],
              [9, 2]
])
B = np.array([
              [7, 9],
              [4, 6],
              [3, 5]
])
A-B

array([[-4, -5],
       [ 0,  2],
       [ 6, -3]])

In [ ]:
2-A ##Broadcasting

array([[-1, -2],
       [-2, -6],
       [-7,  0]])

###Element-wise Multiplication

In [ ]:
A*B
np.multiply(A, B)

array([[21, 36],
       [16, 48],
       [27, 10]])

In [ ]:
2*A

array([[ 6,  8],
       [ 8, 16],
       [18,  4]])

In [ ]:
A@B

ValueError: ignored

#Activity

###Task 1

Create a function named mat_desc() that thoroughly describes a matrix, it should:

1. Displays the shape, size, and rank of the matrix.
2. Displays whether the matrix is square or non-square.
3. Displays whetehr the matrix is an empty matrix.
4. Displays if the matrix is an identity, ones, or zeros matrix.

Use 3 sample matrices in which their shapes are not lower than (3,3). In your methodology, create a flowchart discuss, the functions and methods you have done. Present your results section showing the description of each matrx you have declared. 

###Task 2

Create a function named mat_operations() that takes in two matrices an input parameters it should:

1. Determines if the matrices are viable for operation and returns your own error message if they are not viable.
2. Returns the sum of the matrices.
3. Returns the difference of the matrices.
4. Returns the element-wise multiplication of the matrices.
5. Returns the element-wise division of the matrices.


Use 3 sample matrices in which their shapes are not lower than (3, 3), in your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

#Conclusion