<a href="https://colab.research.google.com/github/esosikeyes/Linear-Algebra_2nd-Sem/blob/main/Assignment_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Linear Algebra for ChE
#Laboratory 5: Matrix Operation



#Objectives
At the end of this activity you will be able to:
1. Be familiar with the fundamental matrix operations.
2. Apply the operations to solve intermediate equations.
3. Apply matrix algebra in engineering solutions.

#Discussion

In [3]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

#Transposition
One of the fundamental operations in matrix algebra is Transposition. The transpose of a matrix is done by flipping the values of its elements over its diagonals. With this, the rows and columns from the original matrix will be switched. So for a matrix $A$ its transpose is denoted as $A^T$. So for example:

$$
A=\begin{bmatrix} 9 & 8 & 7 \\ 6 & {-5} & 4 \\ 3 & {-2} & 1 \end{bmatrix}
$$


$$ A^T = \begin{bmatrix} 9 & 6 & 3\\8 & -5 & -2\\ 7 & 4 & 1\end{bmatrix}$$

This can now be achieved programmatically by using `np.transpose()` or using the `T` method.

In [ ]:
A = np.array([
              [53, 22, 34],
              [77, 83 ,96],
              [20, 32, 44]

])
A

array([[53, 22, 34],
       [77, 83, 96],
       [20, 32, 44]])

In [ ]:
AT1 = np.transpose(A)
AT1

array([[53, 77, 20],
       [22, 83, 32],
       [34, 96, 44]])

In [ ]:
AT2 = A.T
AT2

array([[53, 77, 20],
       [22, 83, 32],
       [34, 96, 44]])

In [ ]:
np.array_equiv(AT1, AT2)

True

In [ ]:
B = np.array([
              [11, 22, 33, 44, 1],
              [55, 66, 77, 88, 2],
              [99, 100, 110, 120, 3]
])
B.shape

(3, 5)

In [ ]:
np.transpose(B).shape

(5, 3)

In [ ]:
B.T.shape

(5, 3)

#Dot Product / Inner Product

The dot product from laboratory activity before, we will try to implement the same operation with matrices. In matrix dot product we are going to get the sum of products of the vectors by row-column pairs. So if we have two matrices $X$ and $Y$:

$$X = \begin{bmatrix}x_{(0,0)}&x_{(0,1)}\\ x_{(1,0)}&x_{(1,1)}\end{bmatrix}, Y = \begin{bmatrix}y_{(0,0)}&y_{(0,1)}\\ y_{(1,0)}&y_{(1,1)}\end{bmatrix}$$

The dot product will then be computed as:
$$X \cdot Y= \begin{bmatrix} x_{(0,0)}*y_{(0,0)} + x_{(0,1)}*y_{(1,0)} & x_{(0,0)}*y_{(0,1)} + x_{(0,1)}*y_{(1,1)} \\  x_{(1,0)}*y_{(0,0)} + x_{(1,1)}*y_{(1,0)} & x_{(1,0)}*y_{(0,1)} + x_{(1,1)}*y_{(1,1)}
\end{bmatrix}$$

We assign values to $X$ and $Y$:
$$X = \begin{bmatrix}1&2\\ 0&1\end{bmatrix}, Y = \begin{bmatrix}-1&0\\ 2&2\end{bmatrix}$$

$$X \cdot Y= \begin{bmatrix} 1*-1 + 2*2 & 1*0 + 2*2 \\  0*-1 + 1*2 & 0*0 + 1*2 \end{bmatrix} = \begin{bmatrix} 3 & 4 \\2 & 2 \end{bmatrix}$$
This could be achieved programmatically using `np.dot()`, `np.matmul()` or the `@` operator.

In [4]:
X = np.array([
              [3, 6],
              [9, 12]      
])

Y = np.array([
              [3, 6, 1, 3, 5],
              [9, 12, 7, 9, 11]      
])

In [5]:
np.array_equiv(X, Y)

False

In [6]:
np.dot(X, Y)

array([[ 63,  90,  45,  63,  81],
       [135, 198,  93, 135, 177]])

In [7]:
X.dot(Y)

array([[ 63,  90,  45,  63,  81],
       [135, 198,  93, 135, 177]])

In [ ]:
X @ Y

array([[ 63,  90,  45,  63,  81],
       [135, 198,  93, 135, 177]])

In [ ]:
np.matmul(X, Y)

array([[ 63,  90,  45,  63,  81],
       [135, 198,  93, 135, 177]])

In [8]:
D = np.array([
              [10, 20, 30],
              [40, 50, 60]
])
E = np.array([
              [70, 80, 90, 100],
              [100, 110, 120, 130],
              [140, 150, 160, 170]
])

In [10]:
D @ E

array([[ 6900,  7500,  8100,  8700],
       [16200, 17700, 19200, 20700]])

In [11]:
D.dot(E)

array([[ 6900,  7500,  8100,  8700],
       [16200, 17700, 19200, 20700]])

In [12]:
np.matmul(D, E)

array([[ 6900,  7500,  8100,  8700],
       [16200, 17700, 19200, 20700]])

In [13]:
np.dot(D, E)

array([[ 6900,  7500,  8100,  8700],
       [16200, 17700, 19200, 20700]])

In matrix dot products there are additional rules compared with vector dot products. Since vector dot products were just in one dimension there are less restrictions. Since now we are dealing with Rank 2 vectors we need to consider some rules:

### Rule 1: The inner dimensions of the two matrices in question must be the same. 

Given a matrix $A$ with a shape of $(a,b)$ where $a$ and $b$ are any integers. If we want to do a dot product between $A$ and another matrix $B$, then matrix $B$ should have a shape of $(b,c)$ where $b$ and $c$ are any integers. So for given the following matrices:

$$A = \begin{bmatrix}2&4\\5&-2\\6&-8\\0&1\end{bmatrix}, B = \begin{bmatrix}1&1\\3&3\\9&-9\\-1&-2\end{bmatrix}, C = \begin{bmatrix}0&1&1\\8&8&8\\1&1&2\end{bmatrix}$$

In this case $A$ has a shape of $(4,2)$, $B$ has a shape of $(4,2)$ and $C$ has a shape of $(3,3)$. So the only matrix pairs that is eligible to perform dot product is matrices $A \cdot C$, or $B \cdot C$.  

In [ ]:
L = np.array([
              [3, 6, 1, 3, 5],
              [9, 12, 7, 9, 11]      
])

M = np.array([
              [2, 4, 5, 6, 7],
              [9, 8, 7, 6, 5]      
])

N = np.array([
              [3, 6, 1, 3, 5],
              [9, 12, 7, 9, 11],
              [12, 24, 36, 42, 54],
              [11, 22, 33, 44, 55],
              [10, 20, 30, 40, 50]

])

In [ ]:
np.dot(L, N)

array([[ 158,  280,  330,  437,  550],
       [ 428,  784,  972, 1265, 1600]])

In [ ]:
np.dot(M, N)

array([[ 238,  452,  618,  796, 1004],
       [ 299,  550,  665,  857, 1091]])

In [ ]:
L @ N

array([[ 158,  280,  330,  437,  550],
       [ 428,  784,  972, 1265, 1600]])

In [ ]:
M @ N

array([[ 238,  452,  618,  796, 1004],
       [ 299,  550,  665,  857, 1091]])

In [ ]:
np.matmul(L, N)

array([[ 158,  280,  330,  437,  550],
       [ 428,  784,  972, 1265, 1600]])

In [ ]:
np.matmul(M, N)

array([[ 238,  452,  618,  796, 1004],
       [ 299,  550,  665,  857, 1091]])

And you can see that when you try to multiply A and B, it returns `ValueError` pertaining to matrix shape mismatch.

### Rule 2: Dot Product has special properties

Dot products are prevalent in matrix algebra, this implies that it has several unique properties and it should be considered when formulation solutions:
 1. $A \cdot B \neq B \cdot A$
 2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
 3. $A\cdot(B+C) = A\cdot B + A\cdot C$
 4. $(B+C)\cdot A = B\cdot A + C\cdot A$
 5. $A\cdot I = A$
 6. $A\cdot \emptyset = \emptyset$ 

In [15]:
A = np.array([
              [3, 6, 1, 3, 5],
              [9, 12, 7, 9, 11],
              [2, 5, 6, 9, 2]      
])

B = np.array([
              [3, 6, 1],
              [9, 12, 5],
              [12, 24, 36],
              [11, 22, 33],
              [10, 20, 30]

])

C = np.array([
              [2, 4, 5],
              [9, 8, 7],
              [10, 15, 34]
])



In [16]:
X = A @ B
X

array([[158, 280, 318],
       [428, 784, 948],
       [242, 454, 600]])

In [17]:
Y = B @ A
Y

array([[ 65,  95,  51,  72,  83],
       [145, 223, 123, 180, 187],
       [324, 540, 396, 576, 396],
       [297, 495, 363, 528, 363],
       [270, 450, 330, 480, 330]])

In [18]:
np.array_equiv(X, Y)

False

In [19]:
C @ (A @ B)

array([[ 3238,  5966,  7428],
       [ 6540, 11970, 14646],
       [16228, 29996, 37800]])

In [20]:
T = A @ (B @ C)
T

array([[ 6016,  7642, 13562],
       [17392, 22204, 39860],
       [10570, 13600, 24788]])

In [22]:
U = (A @ B) @ C
U

array([[ 6016,  7642, 13562],
       [17392, 22204, 39860],
       [10570, 13600, 24788]])

In [23]:
np.array_equal(T, X)

False

In [24]:
np.array_equiv(T, U)

True

#Determinant

A determinant is a scalar value derived from a square matrix. The determinant is a fundamental and important value used in matrix algebra. Although it will not be evident in this laboratory on how it can be used practically, but it will be reatly used in future lessons.

The determinant of some matrix $A$ is denoted as $det(A)$ or $|A|$. So let's say $A$ is represented as:
$$A = \begin{bmatrix}a_{(0,0)}&a_{(0,1)}\\a_{(1,0)}&a_{(1,1)}\end{bmatrix}$$
We can compute for the determinant as:
$$|A| = a_{(0,0)}*a_{(1,1)} - a_{(1,0)}*a_{(0,1)}$$
Thus we have $A$ as:
$$A = \begin{bmatrix}1&4\\0&3\end{bmatrix}, |A| = 3$$

But you might wonder how about square matrices beyond the shape $(2,2)$? We can approach this problem by using several methods such as co-factor expansion and the minors method. This can be taught in the lecture of the laboratory but we can achieve the strenuous computation of high-dimensional matrices programmatically using Python. We can achieve this by using `np.linalg.det()`.

In [ ]:
A = np.array([
              [1, 4],
              [3, 7]
])
np.linalg.det(A)

-5.000000000000001

In [ ]:
B = np.array([
              [1, 4, 5],
              [3, 7, 1],
              [9, 5, 2]
])
np.linalg.det(B)

-219.00000000000003

#Inverse

The inverse of a matrix is another fundamental operation in matrix algebra. Determining the inverse of a matrix let us determine if its solvability and its characteristic as a system of linear equation — we'll expand on this in the nect module. Another use of the inverse matrix is solving the problem of divisibility between matrices. Although element-wise division exists but dividing the entire concept of matrices does not exists. Inverse matrices provides a related operation that could have the same concept of "dividing" matrices.

Now to determine the inverse of a matrix we need to perform several steps. So let's say we have a matrix $M$:
$$M = \begin{bmatrix}1&7\\-3&5\end{bmatrix}$$
First, we need to get the determinant of $M$.
$$|M| = (1)(5)-(-3)(7) = 26$$
Next, we need to reform the matrix into the inverse form:
$$M^{-1} = \frac{1}{|M|} \begin{bmatrix} m_{(1,1)} & -m_{(0,1)} \\ -m_{(1,0)} & m_{(0,0)}\end{bmatrix}$$
That will be:
$$M^{-1} = \frac{1}{26} \begin{bmatrix} 5 & -7 \\ 3 & 1\end{bmatrix} = \begin{bmatrix} \frac{5}{26} & \frac{-7}{26} \\ \frac{3}{26} & \frac{1}{26}\end{bmatrix}$$
For higher-dimension matrices you might need to use co-factors, minors, adjugates, and other reduction techinques. To solve this programmatially we can use `np.linalg.inv()`.

In [28]:
T = np.array([
              [4, 6, 7, 8],
              [8, 7, 6, 5],
              [1, 2, 3, 4],
              [9, 3, 4, 1]

])
np.array(T @ np.linalg.inv(T), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [34]:
Q = np.array([
              [3, 6, 1],
              [9, 12, 7],
              [2, 5, 6]   
])

V = np.linalg.inv(Q)
V

array([[-0.34259259,  0.28703704, -0.27777778],
       [ 0.37037037, -0.14814815,  0.11111111],
       [-0.19444444,  0.02777778,  0.16666667]])

In [37]:
Q @ V

array([[ 1.00000000e+00, -1.21430643e-16, -2.22044605e-16],
       [ 4.99600361e-16,  1.00000000e+00, -1.66533454e-16],
       [ 1.11022302e-16, -6.24500451e-17,  1.00000000e+00]])

In [38]:
## And now let's test your skills in solving a matrix with high dimensions:
N = np.array([
    [18,5,23,1,0,33,5],
    [0,45,0,11,2,4,2],
    [5,9,20,0,0,0,3],
    [1,6,4,4,8,43,1],
    [8,6,8,7,1,6,1],
    [-5,15,2,0,0,6,-30],
    [-2,-5,1,2,1,20,12],
])
N_inv = np.linalg.inv(N)
np.array(N @ N_inv,dtype=int)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

To validate the wether if the matric that you have solved is really the inverse, we follow this dot product property for a matrix $M$:
$$M\cdot M^{-1} = I$$

In [39]:
squad = np.array([
    [2.0, 1.0, 1.5],
    [1.25, 1.0, 1.5],
    [1.75, 1.5, 1.0]
])
weights = np.array([
    [0.2, 0.2, 0.6]
])
p_grade = squad @ weights.T
p_grade

array([[1.5 ],
       [1.35],
       [1.25]])

#Task 1
Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than $(3,3)$.

In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

 1. $A \cdot B \neq B \cdot A$
 2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
 3. $A\cdot(B+C) = A\cdot B + A\cdot C$
 4. $(B+C)\cdot A = B\cdot A + C\cdot A$
 5. $A\cdot I = A$
 6. $A\cdot \emptyset = \emptyset$ 

In [44]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
J = np.array ([
               [19, 18, 17, 16, 15],
               [21, 22, 23, 24, 25],
               [39, 38, 37, 36, 35],
               [41, 42, 43, 44, 45],
               [59, 58, 57, 56, 55]    
])
K = np.array ([
               [91, 92, 93, 94, 95],
               [89, 88, 87, 86, 85],
               [71, 72, 73, 74, 75],
               [69, 68, 67, 66, 65],
               [51, 52, 53, 54, 55]             
])
L = np.array ([
               [15, 16, 17, 18, 19],
               [24, 34, 54, 64, 74],
               [78, 76, 75, 74, 73],
               [34, 35, 36, 37, 38],
               [83, 53, 42, 56, 98]             
])

In [45]:
A = K.dot(J)
B = L.dot(A)
C = A.dot(L)
D = K.dot(L)
W = J.dot(A)
X = K + L
Y = A + J
Z = B + C

In [46]:
print('PROPERTY 1')
{np.array_equiv(A,D)}
print('AB=BA')
print('Matrix AB:')
print(np.matmul(J, K))
print('Matrix BA:')
print(np.matmul(K ,J))
print('APPROVED!')

PROPERTY 1
AB=BA
Matrix AB:
[[ 6407  6424  6441  6458  6475]
 [ 8433  8456  8479  8502  8525]
 [13827 13864 13901 13938 13975]
 [15853 15896 15939 15982 16025]
 [21247 21304 21361 21418 21475]]
Matrix BA:
[[16747 16654 16561 16468 16375]
 [15473 15386 15299 15212 15125]
 [13167 13094 13021 12948 12875]
 [11893 11826 11759 11692 11625]
 [ 9587  9534  9481  9428  9375]]
APPROVED!


In [47]:
print('PROPERTY 2')
{np.array_equiv(K.dot(J),P.dot(A))}
print('A(BC)=(AB)C')
print('Matrix A(BC):')
print(np.matmul(K,J))
print('Matrix (AB)C:')
print(np.matmul(J,A))
print('APPROVED!')

PROPERTY 2
A(BC)=(AB)C
Matrix A(BC):
[[16747 16654 16561 16468 16375]
 [15473 15386 15299 15212 15125]
 [13167 13094 13021 12948 12875]
 [11893 11826 11759 11692 11625]
 [ 9587  9534  9481  9428  9375]]
Matrix (AB)C:
[[1154639 1148198 1141757 1135316 1128875]
 [1520041 1511562 1503083 1494604 1486125]
 [2491979 2478078 2464177 2450276 2436375]
 [2857381 2841442 2825503 2809564 2793625]
 [3829319 3807958 3786597 3765236 3743875]]
APPROVED!


In [48]:
print('PROPERTY 3')
{np.array_equiv(A.dot(L),K)}
print('Matrix A(B+C)')
print(np.matmul(A,L))
print('Matrix (AB)+(AC):')
print(np.add(L,K))
print('APPROVED!')

PROPERTY 3
Matrix A(B+C)
[[3861696 3537079 3706688 4119132 4990076]
 [3567264 3267461 3424192 3805188 4609684]
 [3036256 2781019 2914368 3238652 3923436]
 [2741824 2511401 2631872 2924708 3543044]
 [2210816 2024959 2122048 2358172 2856796]]
Matrix (AB)+(AC):
[[106 108 110 112 114]
 [113 122 141 150 159]
 [149 148 148 148 148]
 [103 103 103 103 103]
 [134 105  95 110 153]]
APPROVED!


In [49]:
print('PROPERTY 4')
{np.array_equiv(J.dot(A),Z)}
print('(B+C)A=(BA)+(CA)')
print('Matrix (B+C)A:')
print(np.matmul(J,A))
print('Matrix (BA)+(CA):')
print(np.add(A,Z))
print('APPROVED!')

PROPERTY 4
(B+C)A=(BA)+(CA)
Matrix (B+C)A:
[[1154639 1148198 1141757 1135316 1128875]
 [1520041 1511562 1503083 1494604 1486125]
 [2491979 2478078 2464177 2450276 2436375]
 [2857381 2841442 2825503 2809564 2793625]
 [3829319 3807958 3786597 3765236 3743875]]
Matrix (BA)+(CA):
[[4997282 4666331 4829606 5235716 6100326]
 [6692355 6375123 6514425 6877992 7665059]
 [8099095 7815617 7920725 8216768 8873311]
 [5143029 4899211 5006287 5285728 5890669]
 [6589021 6378769 6451463 6663192 7137421]]
APPROVED!


In [50]:
print('PROPERTY 5')
{np.array_equiv(K.dot(1),D)}
print('A(1)=A')
print('Matrix A(1):')
print(np.multiply(K,1))
print('Matrix A:')
print(D)
print('APPROVED!')

PROPERTY 5
A(1)=A
Matrix A(1):
[[91 92 93 94 95]
 [89 88 87 86 85]
 [71 72 73 74 75]
 [69 68 67 66 65]
 [51 52 53 54 55]]
Matrix A:
[[21908 19977 20864 23206 28208]
 [20212 18543 19456 21614 26152]
 [17228 15697 16384 18226 22168]
 [15532 14263 14976 16634 20112]
 [12548 11417 11904 13246 16128]]
APPROVED!


In [51]:
print('PROPERTY 6')
{np.array_equiv(J.dot(0),0)}
print('A(0)=0')
print('Matrix A(0):')
print(np.multiply(J,0))
print('APPROVED!')

PROPERTY 6
A(0)=0
Matrix A(0):
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
APPROVED!


#CONCLUSION


In the activity performed about Matrix Operations, the students were able to understand and know all of the Matrix Operations, which are Transposition, Determinant, Inverse, and the Dot Product/Inner Product, including its Rule 1 and Rule 2 that presents the six multiplication properties. It can be inferred that the codes would not work if the proper declaration for each matrix was not used.  The students were also able to put all of their learnings from using Google Colaboratory, Python programming, and solving of Matrix into practice by creating their own sample matrices that show Matrix Operations, and completing Task 1 which aims to make a matrices on the different multiplication properties. Thus, the students clearly defined and explained the entire results made in Google Colaboratory, as well as Task 1. Furthermore, after accomplishing Task 1, the students were possibly done six flow charts that signify how they appropriately know the given task, Python programming, and the six dot product properties. After meeting all of the objectives, the students were able to discern and properly concluded the laboratory report.
